library(patchwork)
library(Seurat)
library(dplyr)
library(future)
plan("multisession", workers = 8)
options(future.globals.maxSize = 8000 * 1024^2)
GCB1.data<-Read10X("D:/GCB1_2.2.filtered_feature_bc_matrix/")
GCB2.data<-Read10X("D:/GCB2_2.2.filtered_feature_bc_matrix/")

GCB1.data<-as.data.frame(GCB1.data)
GCB2.data<-as.data.frame(GCB2.data)

for (i in 1:length(colnames(GCB1.data))) {
  colnames(GCB1.data)[i] <- paste(colnames(GCB1.data)[i],"GCB1",i,sep = "-")  
}

for (i in 1:length(colnames(GCB2.data))) {
  colnames(GCB2.data)[i] <- paste(colnames(GCB2.data)[i],"GCB2",i,sep = "-")  
}

GCB1.metadata<-data.frame(colnames(GCB1.data),rep("GCB1",length(colnames(GCB1.data))))
GCB2.metadata<-data.frame(colnames(GCB2.data),rep("GCB2",length(colnames(GCB2.data))))
colnames(GCB1.metadata)<-c("barcode","group")
colnames(GCB2.metadata)<-c("barcode","group")
rownames(GCB1.metadata)<-GCB1.metadata[,1]
rownames(GCB2.metadata)<-GCB2.metadata[,1]
pbmc.metadata<-rbind(GCB1.metadata,GCB2.metadata)

pbmc.data<-cbind(GCB1.data,GCB2.data)

pbmc <- CreateSeuratObject(counts = pbmc.data, project = "GCB",meta.data = pbmc.metadata,min.cells = 3, min.features = 200)
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^mt-")
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
# pbmc_test <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 6500 & percent.mt < 50). #in the subanalysis use
pbmc_RC <- NormalizeData(pbmc,normalization.method = "RC")
pbmc_CLR<-NormalizeData(pbmc,normalization.method = "CLR")
pbmc <- NormalizeData(pbmc)
pbmc <- FindVariableFeatures(pbmc,selection.method = "vst",nfeatures = 5000)
all.genes <- rownames(pbmc)
pbmc_percent.mt_poisson <- ScaleData(pbmc, features = all.genes,vars.to.regress = "percent.mt",model.use = "poisson")
pbmc_percent.mt_negbinom <- ScaleData(pbmc, features = all.genes,vars.to.regress = "percent.mt",model.use = "negbinom")
pbmc_percent.mt <- ScaleData(pbmc, features = all.genes,vars.to.regress = "percent.mt")
pbmc_nFeature_RNA_poisson <- ScaleData(pbmc, features = all.genes,vars.to.regress = "nFeature_RNA",model.use = "poisson")
pbmc_nFeature_RNA_negbinom <- ScaleData(pbmc, features = all.genes,vars.to.regress = "nFeature_RNA",model.use = "negbinom")
pbmc_nFeature_RNA <- ScaleData(pbmc, features = all.genes,vars.to.regress = "nFeature_RNA")
pbmc_poisson <- ScaleData(pbmc, features = all.genes,model.use = "poisson")
pbmc_negbinom <- ScaleData(pbmc, features = all.genes,model.use = "negbinom")
pbmc <- ScaleData(pbmc, features = all.genes)

pbmc_RC_percent.mt_poisson <- ScaleData(pbmc_RC, features = all.genes,vars.to.regress = "percent.mt",model.use = "poisson")
pbmc_RC_percent.mt_negbinom <- ScaleData(pbmc_RC, features = all.genes,vars.to.regress = "percent.mt",model.use = "negbinom")
pbmc_RC_percent.mt <- ScaleData(pbmc_RC, features = all.genes,vars.to.regress = "percent.mt")
pbmc_RC_nFeature_RNA_poisson <- ScaleData(pbmc_RC, features = all.genes,vars.to.regress = "nFeature_RNA",model.use = "poisson")
pbmc_RC_nFeature_RNA_negbinom <- ScaleData(pbmc_RC, features = all.genes,vars.to.regress = "nFeature_RNA",model.use = "negbinom")
pbmc_RC_nFeature_RNA <- ScaleData(pbmc_RC, features = all.genes,vars.to.regress = "nFeature_RNA")
pbmc_RC_poisson <- ScaleData(pbmc_RC, features = all.genes,model.use = "poisson")
pbmc_RC_negbinom <- ScaleData(pbmc_RC, features = all.genes,model.use = "negbinom")
pbmc_RC <- ScaleData(pbmc_RC, features = all.genes)
saveRDS(pbmc_percent.mt_poisson,"pbmc_percent.mt_poisson.rds")
saveRDS(pbmc_percent.mt_negbinom,"pbmc_percent.mt_negbinom.rds")
saveRDS(pbmc_percent.mt,"pbmc_percent.mt.rds")
saveRDS(pbmc_nFeature_RNA_poisson,"pbmc_nFeature_RNA_poisson.rds")
saveRDS(pbmc_nFeature_RNA_negbinom,"pbmc_nFeature_RNA_negbinom.rds")
saveRDS(pbmc_nFeature_RNA,"pbmc_nFeature_RNA.rds")
saveRDS(pbmc_RC_percent.mt_poisson,"pbmc_RC_percent.mt_poisson.rds")
saveRDS(pbmc_RC_percent.mt_negbinom,"pbmc_RC_percent.mt_negbinom.rds")
saveRDS(pbmc_RC_percent.mt,"pbmc_RC_percent.mt.rds")
saveRDS(pbmc_RC_nFeature_RNA_poisson,"pbmc_RC_nFeature_RNA_poisson.rds")
saveRDS(pbmc_RC_nFeature_RNA_negbinom,"pbmc_RC_nFeature_RNA_negbinom.rds")
saveRDS(pbmc_RC_nFeature_RNA,"pbmc_RC_nFeature_RNA.rds")
saveRDS(pbmc_RC_poisson,"pbmc_RC_poisson.rds")
saveRDS(pbmc_RC_negbinom,"pbmc_RC_negbinom.rds")
saveRDS(pbmc_RC,"pbmc_RC.rds")
saveRDS(pbmc_poisson,"pbmc_poisson.rds")
saveRDS(pbmc_negbinom,"pbmc_negbinom.rds")
saveRDS(pbmc,"pbmc.rds")

pbmc_CLR_percent.mt_poisson <- ScaleData(pbmc_CLR, features = all.genes,vars.to.regress = "percent.mt",model.use = "poisson")
pbmc_CLR_percent.mt_negbinom <- ScaleData(pbmc_CLR, features = all.genes,vars.to.regress = "percent.mt",model.use = "negbinom")
pbmc_CLR_percent.mt <- ScaleData(pbmc_CLR, features = all.genes,vars.to.regress = "percent.mt")
pbmc_CLR_nFeature_RNA_poisson <- ScaleData(pbmc_CLR, features = all.genes,vars.to.regress = "nFeature_RNA",model.use = "poisson")
saveRDS(pbmc_CLR_percent.mt_poisson,"pbmc_CLR_percent.mt_poisson.rds")
saveRDS(pbmc_CLR_percent.mt_negbinom,"pbmc_CLR_percent.mt_negbinom.rds")
saveRDS(pbmc_CLR_percent.mt,"pbmc_CLR_percent.mt.rds")
saveRDS(pbmc_CLR_nFeature_RNA_poisson,"pbmc_CLR_nFeature_RNA_poisson.rds")

pbmc_CLR_nFeature_RNA_negbinom <- ScaleData(pbmc_CLR, features = all.genes,vars.to.regress = "nFeature_RNA",model.use = "negbinom")
pbmc_CLR_nFeature_RNA <- ScaleData(pbmc_CLR, features = all.genes,vars.to.regress = "nFeature_RNA")
pbmc_CLR_poisson <- ScaleData(pbmc_CLR, features = all.genes,model.use = "poisson")
pbmc_CLR_negbinom <- ScaleData(pbmc_CLR, features = all.genes,model.use = "negbinom")
saveRDS(pbmc_CLR_nFeature_RNA_negbinom,"pbmc_CLR_nFeature_RNA_negbinom.rds")
saveRDS(pbmc_CLR_nFeature_RNA,"pbmc_CLR_nFeature_RNA.rds")
saveRDS(pbmc_CLR_poisson,"pbmc_CLR_poisson.rds")
saveRDS(pbmc_CLR_negbinom,"pbmc_CLR_negbinom.rds")
pbmc_CLR <- ScaleData(pbmc_CLR, features = all.genes)
saveRDS(pbmc_CLR,"pbmc_CLR.rds")
